config/routes.rb
Rails.application.routes.draw do
  resources :parties

  resources :applicants

  root 'users#index'
  get 'homes/index'
 
  devise_for :users
  patch 'users/:id' => 'users#update'
  get 'users/dashboard' => 'users#index'
  resources :tasks

  resources :cymbals do 
    collection do
      get :move
    end
  end

  resources :toys do 
    collection do
      get :move
    end
  end

  resources :group_users

  resources :groups, only: [:index, :create, :destroy, :edit, :new ,:show]  do
    member do
      patch :restore
      delete :reallyDestroy
    end
  end

  post 'groups/createAjax' => 'groups#createAjax'

  resources :users, only: [:index, :create, :destroy, :edit, :new, :show] do
    member do
      patch :restore
      delete :reallyDestroy
    end
  end
  
  resources :posts do
    resources :comments, only: [:new, :create, :destroy, :edit, :update]
  end

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.role == "admin"
        can :manage, :all
    elsif user.role == "moderator"
        can :read, Post
        can [:create, :update, :destroy], [Post, Comment]
    elsif user.role == "user"
        can :read, Post
        can :create, [Post, Comment]
        can [:update, :destroy], [Post, Comment], user_id: user.id
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
end
end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/cymbal.rb
class Cymbal < ActiveRecord::Base
	acts_as_list
	scope :sorted, -> {order('position ASC')}
end

app/models/group.rb
class Group < ActiveRecord::Base
	acts_as_paranoid
	self.per_page = 5
	has_many :group_users, dependent: :destroy
	has_many :users, through: :group_users
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
	acts_as_paranoid
	belongs_to :user
	belongs_to :group
end

app/models/party.rb
class Party < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
	
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, :dependent => :destroy 
	belongs_to :user, :dependent => :destroy 
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/toy.rb
class Toy < ActiveRecord::Base
	acts_as_list
	scope :sorted, -> {order('position ASC')}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
	acts_as_paranoid

	has_many :group_users, dependent: :destroy
	has_many :groups, through: :group_users
	
	has_many :posts
	has_many :comments
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  before_action :set_toy, only: [:show, :edit, :update, :destroy]
  layout 'bootstrap'
  # GET /toys
  # GET /toys.json
  def move
    @toy = Toy.where(position: params[:first_position]).first
    @toy.insert_at(params[:second_position].to_i)
    @toys = Toy.sorted
    respond_to do |f|
      f.js
    end
  end


  def index
    @toys = Toy.all.sorted
  end

  # GET /toys/1
  # GET /toys/1.json
  def show
  end

  # GET /toys/new
  def new
    @toy = Toy.new
  end

  # GET /toys/1/edit
  def edit
  end

  # POST /toys
  # POST /toys.json
  def create
    @toy = Toy.new(toy_params)

    respond_to do |format|
      if @toy.save
        format.html { redirect_to @toy, notice: 'Toy was successfully created.' }
        format.json { render :show, status: :created, location: @toy }
      else
        format.html { render :new }
        format.json { render json: @toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /toys/1
  # PATCH/PUT /toys/1.json
  def update
    respond_to do |format|
      if @toy.update(toy_params)
        format.html { redirect_to @toy, notice: 'Toy was successfully updated.' }
        format.json { render :show, status: :ok, location: @toy }
      else
        format.html { render :edit }
        format.json { render json: @toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toys/1
  # DELETE /toys/1.json
  def destroy
    @toy.destroy
    respond_to do |format|
      format.html { redirect_to toys_url, notice: 'Toy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_toy
      @toy = Toy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def toy_params
      params.require(:toy).permit(:name, :photo, :position)
    end
  end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/helpers/cymbals_helper.rb
module CymbalsHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/toys/_form.html.erb
<%= form_for(@toy) do |f| %>
  <% if @toy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@toy.errors.count, "error") %> prohibited this toy from being saved:</h2>

      <ul>
      <% @toy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/toys/_toy.html.erb
<li class="well" id="toy-<%=toy.id%>">
	<%= toy.name %>
	<%= toy.position %>
	<img src="<%= toy.photo %>" style="width:100px" alt="">
	<%= link_to 'Show', toy %>
	<%= link_to 'Edit', edit_toy_path(toy) %>
	<%= link_to 'Destroy', toy, method: :delete, data: { confirm: 'Are you sure?' } %>
</li>

app/views/toys/edit.html.erb
<h1>Editing Toy</h1>

<%= render 'form' %>

<%= link_to 'Show', @toy %> |
<%= link_to 'Back', toys_path %>

app/views/toys/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Toys</h1>
<ul id="sortable">
  <%= render @toys %>
</ul>
<%= link_to 'New Toy', new_toy_path %>
<script type="text/javascript">
$(function(){
  var first_position;
  var second_position;
  $("#sortable").sortable({

    start: function (event,ui){
      first_position =ui.item.index();
      console.log(ui.item.index())},

    stop: function (event,ui){
      second_position = ui.item.index();
      console.log(ui.item.index());

      $.ajax({
        url: '<%= move_toys_path%>',
        type: 'GET',
        dataType: 'script',
        data: {first_position: first_position,
          second_position: second_position}
      })
      .done(function() {
        console.log("success");
      })
      .fail(function() {
        console.log("error");
      })
      .always(function() {
        console.log("complete");
      });}

    });

  $("#sortable").disableSelection();
});

</script>

app/views/toys/move.js.erb
$('#sortable').html("<%= j render @toys %>");

app/views/toys/new.html.erb
<h1>New Toy</h1>

<%= render 'form' %>

<%= link_to 'Back', toys_path %>

app/views/toys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @toy.name %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @toy.photo %>
</p>

<%= link_to 'Edit', edit_toy_path(@toy) %> |
<%= link_to 'Back', toys_path %>