config/routes.rb
Rails.application.routes.draw do
  resources :parties

  resources :applicants

  root 'users#index'
  get 'homes/index'
 
  devise_for :users
  patch 'users/:id' => 'users#update'
  get 'users/dashboard' => 'users#index'
  resources :tasks

  resources :cymbals do 
    collection do
      get :move
    end
  end

  resources :toys do 
    collection do
      get :move
    end
  end

  resources :group_users

  resources :groups, only: [:index, :create, :destroy, :edit, :new ,:show]  do
    member do
      patch :restore
      delete :reallyDestroy
    end
  end

  post 'groups/createAjax' => 'groups#createAjax'

  resources :users, only: [:index, :create, :destroy, :edit, :new, :show] do
    member do
      patch :restore
      delete :reallyDestroy
    end
  end
  
  resources :posts do
    resources :comments, only: [:new, :create, :destroy, :edit, :update]
  end

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.role == "admin"
        can :manage, :all
    elsif user.role == "moderator"
        can :read, Post
        can [:create, :update, :destroy], [Post, Comment]
    elsif user.role == "user"
        can :read, Post
        can :create, [Post, Comment]
        can [:update, :destroy], [Post, Comment], user_id: user.id
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
end
end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/cymbal.rb
class Cymbal < ActiveRecord::Base
	acts_as_list
	scope :sorted, -> {order('position ASC')}
end

app/models/group.rb
class Group < ActiveRecord::Base
	acts_as_paranoid
	self.per_page = 5
	has_many :group_users, dependent: :destroy
	has_many :users, through: :group_users
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
	acts_as_paranoid
	belongs_to :user
	belongs_to :group
end

app/models/party.rb
class Party < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
	
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, :dependent => :destroy 
	belongs_to :user, :dependent => :destroy 
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/toy.rb
class Toy < ActiveRecord::Base
	acts_as_list
	scope :sorted, -> {order('position ASC')}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
	acts_as_paranoid

	has_many :group_users, dependent: :destroy
	has_many :groups, through: :group_users
	
	has_many :posts
	has_many :comments
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  
  #If you want to do some action before destroy
  #be#fore_destroy :some_method
  #Same, but before restore
  #before_restore :callback_name_goes_here

  layout 'bootstrap'
  # GET /groups
  # GET /groups.json
  def index
    if params[:q]
    @groups = Group.where("name like ?", "%#{params[:q]}%").includes(:users).paginate(:page => params[:page]) 
    else
    @groups = Group.all.includes(:users).paginate(:page => params[:page])
    end
    @lastOnList = @groups.size > 0? @groups.last : Group.new 
    @deletedGroups = Group.only_deleted
    @group = Group.new
    
    respond_to do |f|
      f.html
      f.js
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    respond_to do |format|
      if @group.save
        flash[:success] = 'Todo was successfully created.'
        format.html { redirect_to @group }
        format.json { render :show, status: :created, location: @group }
      else
        flash[:danger] = 'There was a problem creating the Group.'
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def createAjax
    @group = Group.new(group_params)
    @appendId = last_params[:last_id]
    @group.save 
    respond_to do |f|
      f.js 
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        flash[:success] = 'Grupo was successfully updated.'
        format.html { redirect_to @group}
        format.json { render :show, status: :ok, location: @group }
      else
        flash[:danger] = 'There was a problem updating the Grupo.'
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
    flash[:success] = 'Grupo was successfully destroyed.'
     format.html { redirect_to groups_url}
     format.json { head :no_content }
   end
 end

 def restore
    respond_to do |format|
      if Group.with_deleted.find(params[:id]).restore(:recursive => true)
        flash[:success] = "Group restored successfully" 
        format.html { redirect_to groups_url }
      else
        flash[:danger] = "There was a problem restoring the User" 
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end  
    end
  end

  def reallyDestroy
    Group.with_deleted.find(params[:id]).really_destroy!
    respond_to do |format|
      flash[:success] = "Group realy destroyed successfully" 
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

 private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
    def last_params
      params.require(:group).permit(:last_id)
    end
  end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/helpers/cymbals_helper.rb
module CymbalsHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_buscador.html.erb
<%= form_for(Group.new, url:'groups/createAjax.js', :html => {:class => "form-inline"}, remote: true ) do |f| %>
  <div class="field from-group">
    <%= f.text_field :name, class: "form-control", id: "datepicker" %>
  </div>
<% end %>

app/views/groups/_buscador2.html.erb
<%= form_tag groups_path, method: "GET" do %>
<%= text_field_tag :q %>
<% end %>

<script type="text/javascript">
$("input[name=q]").on( "input", function(){
	var search = this.value;
	if (search.length >=3 || search.length == 0){
		$.ajax({
			url: '<%= groups_path %>',
			type: 'GET',
			dataType: 'script',
			data: {q: search},
		})
		.done(function() {
			console.log("success");
		})
		.fail(function() {
			console.log("error");
		})
		.always(function() {
			console.log("complete");
		});
	}	
});
</script>

app/views/groups/_deletedGroup.html.erb
<tr>
	<td><%= deletedGroup.name %></td>
   	<td><%= link_to 'Show', deletedGroup %></td>
   	<td><%= link_to 'Edit', edit_group_path(deletedGroup) %></td>
    <td><%= link_to 'Restore', restore_group_path(deletedGroup.id), :method => :patch %></td>
    <td><%= link_to 'Really Destroy', reallyDestroy_group_path(deletedGroup.id), :method => :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/groups/_form.html.erb
<%= form_for(@group, :html => {:class => "form-inline"} ) do |f| %>
<% if @group.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
  <ul>
    <% @group.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
  <div class="field from-group">
    <%= f.label :name%>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.submit class:'btn btn-primary'%>
  </div>
<% end %>

app/views/groups/_formAjax.html.erb
<%= form_for(Group.new, url:'groups/createAjax.js', :html => {:class => "form-inline"}, remote: true ) do |f| %>
  <div class="field from-group">
    <%= f.label :'nuevo grupo'%>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.hidden_field(:last_id, :value => @lastOnList.id)%>
    <%= f.submit class:'btn btn-primary'%>
  </div>
<% end %>

app/views/groups/_group.html.erb
<tr id= "group-<%= group.id%>" >
  <div class="accordion-group">
    <td class="accordion-heading" data-toggle="collapse" href="#<%= group.id%>"><%= group.name %></td>
    <td><%= link_to 'Show', group %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <tr id="<%=group.id%>" class="accordion-inner collapse"><td colspan="5">
      <%= render 'innerTable', group: group %></td>
    </tr>
  </tr>
</div>

app/views/groups/_innerTable.html.erb
<table class = "table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr class = "info">
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% group.users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
    </tr>
  </div>
  <% end %>
</tbody>
</table>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="row"><div class="col-md-7"><h4><%= render 'buscador2' %></h4></div>
  <div class="col-md-5"><h4><%= render 'formAjax' %></h4></div>
</div>

<table id="groups" class = "table gittable-bordered table-hover table-condensed">
  <thead>
    <tr class = "info">
      <th>Name</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>
  <tbody id="bodyGroups">
    <%= render @groups %>
  </tbody>
</table>

<%= will_paginate @groups %>
<br>

<h1>Listing Deleted Groups</h1>
<table class = "table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr class = "info">
      <th>Name</th>
      <th colspan="4">Action</th>
    </tr>
  </thead>
  <tbody>
<%= render partial: "deletedGroup", collection: @deletedGroups %>
    </tbody>
</table>


<script type="text/javascript">
$("#groups tbody").sortable().disableSelection();
</script>

app/views/groups/index.js.erb
$("#bodyGroups").html("<%= j render @groups %>")

app/views/groups/new.html.erb
<h1>New Group</h1>
<%= render 'form' %>

app/views/groups/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>