config/routes.rb
Rails.application.routes.draw do
  resources :parties

  resources :applicants

  root 'users#index'
  get 'homes/index'
 
  devise_for :users
  patch 'users/:id' => 'users#update'
  get 'users/dashboard' => 'users#index'
  resources :tasks

  resources :cymbals do 
    collection do
      get :move
    end
  end

  resources :toys do 
    collection do
      get :move
    end
  end

  resources :group_users

  resources :groups, only: [:index, :create, :destroy, :edit, :new ,:show]  do
    member do
      patch :restore
      delete :reallyDestroy
    end
  end

  post 'groups/createAjax' => 'groups#createAjax'

  resources :users, only: [:index, :create, :destroy, :edit, :new, :show] do
    member do
      patch :restore
      delete :reallyDestroy
    end
  end
  
  resources :posts do
    resources :comments, only: [:new, :create, :destroy, :edit, :update]
  end

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.role == "admin"
        can :manage, :all
    elsif user.role == "moderator"
        can :read, Post
        can [:create, :update, :destroy], [Post, Comment]
    elsif user.role == "user"
        can :read, Post
        can :create, [Post, Comment]
        can [:update, :destroy], [Post, Comment], user_id: user.id
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
end
end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/cymbal.rb
class Cymbal < ActiveRecord::Base
	acts_as_list
	scope :sorted, -> {order('position ASC')}
end

app/models/group.rb
class Group < ActiveRecord::Base
	acts_as_paranoid
	self.per_page = 5
	has_many :group_users, dependent: :destroy
	has_many :users, through: :group_users
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
	acts_as_paranoid
	belongs_to :user
	belongs_to :group
end

app/models/party.rb
class Party < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
	
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, :dependent => :destroy 
	belongs_to :user, :dependent => :destroy 
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/toy.rb
class Toy < ActiveRecord::Base
	acts_as_list
	scope :sorted, -> {order('position ASC')}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
	acts_as_paranoid

	has_many :group_users, dependent: :destroy
	has_many :groups, through: :group_users
	
	has_many :posts
	has_many :comments
end

app/controllers/cymbals_controller.rb
class CymbalsController < ApplicationController
  before_action :set_cymbal, only: [:show, :edit, :update, :destroy]
  layout 'bootstrap'

  def move
    @cymbal = Cymbal.where(position: params[:first_position]).first
    @cymbal.insert_at(params[:second_position].to_i)
    @cymbals = Cymbal.sorted
    respond_to do |f|
      f.js
    end
  end

  # GET /cymbals
  # GET /cymbals.json
  def index
    @cymbals = Cymbal.sorted
  end

  # GET /cymbals/1
  # GET /cymbals/1.json
  def show
  end

  # GET /cymbals/new
  def new
    @cymbal = Cymbal.new
  end

  # GET /cymbals/1/edit
  def edit
  end

  # POST /cymbals
  # POST /cymbals.json
  def create
    @cymbal = Cymbal.new(cymbal_params)

    respond_to do |format|
      if @cymbal.save
        format.html { redirect_to @cymbal, notice: 'Cymbal was successfully created.' }
        format.json { render :show, status: :created, location: @cymbal }
      else
        format.html { render :new }
        format.json { render json: @cymbal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cymbals/1
  # PATCH/PUT /cymbals/1.json
  def update
    respond_to do |format|
      if @cymbal.update(cymbal_params)
        format.html { redirect_to @cymbal, notice: 'Cymbal was successfully updated.' }
        format.json { render :show, status: :ok, location: @cymbal }
      else
        format.html { render :edit }
        format.json { render json: @cymbal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cymbals/1
  # DELETE /cymbals/1.json
  def destroy
    @cymbal.destroy
    respond_to do |format|
      format.html { redirect_to cymbals_url, notice: 'Cymbal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cymbal
      @cymbal = Cymbal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cymbal_params
      params.require(:cymbal).permit(:CymbalType, :family, :inches, :name, :image,:sound, :position)
    end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/helpers/cymbals_helper.rb
module CymbalsHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cymbals/_cymbal.html.erb
<tr>
	<td><%= cymbal.position %></td>
	<td><%= cymbal.CymbalType %></td>
	<td><%= cymbal.family %></td>
	<td><%= cymbal.inches %></td>
	<td><%= cymbal.name %></td>
	<td><image src="<%= cymbal.image %>" style="width:75px" alt=""</td>
	<td><audio controls>
		<source src="<%= asset_path cymbal.sound%>" type="audio/ogg">
		<source src="<%= asset_path cymbal.sound%>" type="audio/wav">
		<source src="<%= asset_path cymbal.sound%>" type="audio/mpeg">
				Your browser does not support the audio element.
		</audio>
	</td>
	<td><%= link_to 'Show', cymbal %></td>
	<td><%= link_to 'Edit', edit_cymbal_path(cymbal) %></td>
	<td><%= link_to 'Destroy', cymbal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/cymbals/_form.html.erb
<%= form_for(@cymbal) do |f| %>
  <% if @cymbal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cymbal.errors.count, "error") %> prohibited this cymbal from being saved:</h2>

      <ul>
      <% @cymbal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :CymbalType %>
  </div>
  <div class="field">
    <%= f.label :family %><br>
    <%= f.text_field :family %>
  </div>
  <div class="field">
    <%= f.label :inches %><br>
    <%= f.number_field :inches %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :sound %><br>
    <%= f.text_field :sound %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cymbals/edit.html.erb
<h1>Editing Cymbal</h1>

<%= render 'form' %>

<%= link_to 'Show', @cymbal %> |
<%= link_to 'Back', cymbals_path %>

app/views/cymbals/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Cymbals</h1>
<table class= "table" id='sort'>
  <thead>
    <tr>
      <th>Position</th>
      <th>Type</th>
      <th>Family</th>
      <th>Inches</th>
      <th>Name</th>
      <th>Image</th>
      <th>Sound</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @cymbals %>
  </tbody>
</table>
<br>
<script type="text/javascript">
$(function(){
  var first_position;
  var second_position;
  $("#sort tbody").sortable({
    
    start: function(event,ui){
      first_position=ui.item.index();
      console.log(ui.item.index())},

    stop: function(event,ui){
      second_position = ui.item.index();
      console.log(ui.item.index());
      $.ajax({
        url: '<%= move_cymbals_path%>',
        type: 'GET',
        dataType: 'script',
        data: {first_position: first_position,
          second_position: second_position}
      })
      .done(function() {
        console.log("success");
      })
      .fail(function() {
        console.log("error");
      })
      .always(function() {
        console.log("complete");
      });}

    });
  $("#sort tbody").disableSelection();
});
</script>
<%= link_to 'New Cymbal', new_cymbal_path %>

app/views/cymbals/move.js.erb
$('#sort').html("<%= j render @cymbals %>");

app/views/cymbals/new.html.erb
<h1>New Cymbal</h1>

<%= render 'form' %>

<%= link_to 'Back', cymbals_path %>

app/views/cymbals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @cymbal.CymbalType %>
</p>

<p>
  <strong>Family:</strong>
  <%= @cymbal.family %>
</p>

<p>
  <strong>Inches:</strong>
  <%= @cymbal.inches %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cymbal.name %>
</p>

<%= link_to 'Edit', edit_cymbal_path(@cymbal) %> |
<%= link_to 'Back', cymbals_path %>